const abbreviationMap = {
  "Royal Melbourne Institute of Technology": ["RMIT", "Royal Melbourne", "Royal Melbourne Tech"],
  "University of Melbourne": ["Unimelb", "UoM", "Melbourne University", "Melbourne Uni"],
  "Monash University": ["Monash", "Monash Uni"],
  "University of Sydney": ["USYD", "Sydney University", "Sydney Uni", "Sydney U", "usyd"],
  "University of New South Wales": ["UNSW", "New South Wales Uni", "NSW Uni"],
  "University of Queensland": ["UQ", "Queensland University", "Queensland Uni"],
  "University of Western Australia": ["UWA", "Western Australia Uni", "WA Uni"],
  "University of Adelaide": ["Adelaide University", "Adelaide Uni", "UofA"],
  "The Australian National University": ["ANU", "National University", "Canberra Uni"],
  "University of Technology Sydney": ["UTS", "Technology Sydney", "Tech Sydney"],
  "University of Newcastle": ["UON", "Newcastle Uni", "Newcastle University"],
  "University of Wollongong": ["UOW", "Wollongong Uni", "Wollongong University"],
  "Macquarie University": ["Macquarie", "Macquarie Uni", "MQ"],
  "Curtin University": ["Curtin", "Curtin Uni"],
  "Griffith University": ["Griffith", "Griffith Uni"],
  "Queensland University of Technology": ["QUT", "Queensland Tech", "Q Tech"],
  "La Trobe University": ["La Trobe", "La Trobe Uni"],
  "Deakin University": ["Deakin", "Deakin Uni"],
  "University of Tasmania": ["UTAS", "Tasmania University", "Tas Uni"],
  "Flinders University": ["Flinders", "Flinders Uni"],
  "James Cook University": ["JCU", "James Cook", "Cook University"],
  "Charles Sturt University": ["CSU", "Charles Sturt", "Sturt Uni"],
  "University of Canberra": ["UC", "Canberra Uni"],
  "Swinburne University of Technology": ["Swinburne", "Swinburne Uni", "Swin"],
  "Edith Cowan University": ["ECU", "Edith Cowan", "ECU Perth"],
  "Southern Cross University": ["SCU", "Southern Cross", "Southern Cross Uni"],
  "Bond University": ["Bond", "Bond Uni"],
  "Murdoch University": ["Murdoch", "Murdoch Uni"],
  "Victoria University": ["VU", "Victoria Uni", "VU Melbourne"],
  "University of Southern Queensland": ["USQ", "Southern Queensland Uni", "Toowoomba Uni"],
  "University of the Sunshine Coast": ["USC", "Sunshine Coast Uni"],
  "Charles Darwin University": ["CDU", "Darwin Uni"]
};

export default abbreviationMap;